Update forge_api_deploy_dev.yml

diff --git a/.github/workflows/forge_api_deploy_dev.yml b/.github/workflows/forge_api_deploy_dev.yml
--- a/.github/workflows/forge_api_deploy_dev.yml
+++ b/.github/workflows/forge_api_deploy_dev.yml
@@ -71,9 +71,19 @@ jobs:
           version=$(ls -tr pkg | tail -1)
           eval "$(ssh-agent -s)"
           ssh-add ~/.ssh/id_rsa
-          echo "Starting deploy to dev"
-          cd /home/runner/work/puppet-forge-api/puppet-forge-api && bundle exec harrison deploy pkg/$version --env dev --no-confirm 
-          echo "Successfully deployed to dev"
+
+          if [ "${{ github.event.label.name }}" == "deploy_dev" ]; then
+            echo "Deploying to dev environment"
+            cd /home/runner/work/puppet-forge-api/puppet-forge-api && bundle exec harrison deploy pkg/$version --env dev --no-confirm
+            echo "Successfully deployed to dev"
+          elif [ "${{ github.event.label.name }}" == "deploy_stage" ]; then
+            echo "Deploying to stage environment"
+            cd /home/runner/work/puppet-forge-api/puppet-forge-api && bundle exec harrison deploy pkg/$version --env stage --no-confirm
+            echo "Successfully deployed to stage"
+          else
+            echo "Invalid label for deployment"
+            exit 1
+          fi
 
       - name: Comment PR
         uses: thollander/actions-comment-pull-request@v2
